// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Wo3qWRT0PJWtSlMkmT7hvTb0BHyK2XQ',
    appId: '1:1051075808560:web:6daa1b26b2f0f9e67f0cf5',
    messagingSenderId: '1051075808560',
    projectId: 'flutter-uber-clone-with-dc2f6',
    authDomain: 'flutter-uber-clone-with-dc2f6.firebaseapp.com',
    storageBucket: 'flutter-uber-clone-with-dc2f6.appspot.com',
    measurementId: 'G-CJ7RS0XZ38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9KSAYGlOq4G848lUkWm0MV-So61B5Q_s',
    appId: '1:1051075808560:android:f95549bd954c7f777f0cf5',
    messagingSenderId: '1051075808560',
    projectId: 'flutter-uber-clone-with-dc2f6',
    storageBucket: 'flutter-uber-clone-with-dc2f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2xwOK37t4MDXlPJbjpGn9h0WPa_x_KG4',
    appId: '1:1051075808560:ios:afa861742bd2ccb27f0cf5',
    messagingSenderId: '1051075808560',
    projectId: 'flutter-uber-clone-with-dc2f6',
    storageBucket: 'flutter-uber-clone-with-dc2f6.appspot.com',
    iosBundleId: 'com.example.uberAppCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2xwOK37t4MDXlPJbjpGn9h0WPa_x_KG4',
    appId: '1:1051075808560:ios:afa861742bd2ccb27f0cf5',
    messagingSenderId: '1051075808560',
    projectId: 'flutter-uber-clone-with-dc2f6',
    storageBucket: 'flutter-uber-clone-with-dc2f6.appspot.com',
    iosBundleId: 'com.example.uberAppCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Wo3qWRT0PJWtSlMkmT7hvTb0BHyK2XQ',
    appId: '1:1051075808560:web:ed1940b862541d907f0cf5',
    messagingSenderId: '1051075808560',
    projectId: 'flutter-uber-clone-with-dc2f6',
    authDomain: 'flutter-uber-clone-with-dc2f6.firebaseapp.com',
    storageBucket: 'flutter-uber-clone-with-dc2f6.appspot.com',
    measurementId: 'G-S3XC112MDE',
  );
}
